### ISSUE TITLE
(IAC-570) vSphere - Missing IPs in Terraform output when using DHCP for NFS & Jump

### ISSUE THREAD

**Issue by jarpat** [sassoftware/viya4-iac-k8s#1]
### Terraform Version

```bash
1.1.9 # From Docker Container
```

### Terraform Variable File

```terraform
..truncated
# Jump server
#
#   Suggested server specs shown below.
#
create_jump    = true # Creation flag
jump_num_cpu   = 4    # 4 CPUs
jump_ram       = 8092 # 8 GB
jump_disk_size = 100  # 100 GB
jump_ip        = ""   # Assigned values for static IPs

# NFS server
#
#   Suggested server specs shown below.
#
create_nfs    = true  # Creation flag
nfs_num_cpu   = 8     # 8 CPUs
nfs_ram       = 16384 # 16 GB
nfs_disk_size = 500   # 500 GB
nfs_ip        = ""    # Assigned values for static IPs
```

### Steps to Reproduce

1. `docker run --rm -it   --group-add root   --user $(id -u):$(id -g)   --env-file /home/$MYUSER/.vsphere/.vsphere_creds.env   --volume $(pwd):/workspace   viya4-iac-k8s:local install vsphere`

### Expected Behavior

In the Terraform output I expect `nfs_public_ip` & `jump_public_ip` to be populated with values

### Actual Behavior

Those fields are not populated, so we run into an error when the ansible playbook executes
```bash
TASK [kubernetes/storage/nfs-subdir-external-provisioner : Setting up default storage for cluster using nfs-subdir-external-provisioner] *******************************************************************************************************************************************************************************
Monday 16 May 2022  16:33:49 +0000 (0:00:00.568)       0:04:34.018 ************ 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {'nfs': {'server': '{{ nfs_ip }}', 'path': '/srv/nfs/kubernetes/sc/default', 'mountOptions': ['noatime', 'nodiratime', 'rsize=262144', 'wsize=262144']}, 'storageClass': {'archiveOnDelete': 'false', 'de
faultClass': 'true', 'name': 'default'}}: 'nfs_ip' is undefined\n\nThe error appears to be in '/viya4-iac-k8s/roles/kubernetes/storage/nfs-subdir-external-provisioner/tasks/main.yaml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:
\n\n#\n- name: Setting up default storage for cluster using nfs-subdir-external-provisioner\n  ^ here\n"}
```

### Additional Context

I tried removing `nfs_ip` & `jump_ip` from .tfvars so they they would instead default to null in hopes that was the proper way to do this instead  Terraform fails with the following:

```bash
│ Call to function "templatefile" failed: ./templates/ansible/ansible-vars.yaml.tmpl:45,14-21: Invalid function argument; Invalid value for "value" parameter: argument must not be null., and 1 other diagnostic(s).

```

### References

- n/a

-->

**Comment by thpang** [comment]
After reading over this one carefully, it's not an issue. According to the variable file provided there no IP address was provided for either the jump or nfs server. If the samples, notes, and description need to be updated. I am fine with that. @jarpat your thoughts?

**Comment by jarpat** [comment]
I believe I initially thought the behavior when setting the variables to an empty string (e.g. `jump_ip=""`), it would result in a dynamically assigned IP address. Looking at the doc again it does specifically say "Static IP address for X server"  for each of these variables so it does look it requires a IP value to be set.

**Comment by thpang** [comment]
I thought the same thing as well. The docs need to be clearer and those fields need to be required. Keeping this one open so that info can be updated.

**Comment by thpang** [comment]
Both the description and sample files state a static IP is needed for these entries. Closing this one.
