### ISSUE TITLE
Update docs to include more info on Cluster VIP and Cloud Provider

### ISSUE THREAD

**Issue by thpang** [sassoftware/viya4-iac-k8s#11]
Clarification on kube_vip and kubernets_vip items in the terraform and ansible files. There are new concepts for folks not used to managing a full cluster from scratch. Need more doc and explanations on these items.

**Comment by gkoutsog** [comment]
Since kube_vip is an add-on to upstream kubernetes, documentation for this module is more than recommended, would even say required. Please write more info on how this piece of software is used in this project and how to troubleshoot it.

**Comment by jarpat** [comment]
We do have some doc here in our [CONFIG-VARS.md](https://github.com/sassoftware/viya4-iac-k8s/blob/main/docs/CONFIG-VARS.md#kubernetes-cluster-virtual-ip-address) that explains the `kube_vip` and `kubernets_vip` items that have been written since this creation of this issue that should cover this.
