### ISSUE TITLE
docs: (IAC-1244) jmespath requirement not listed

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-k8s#15]
I'm using the tool for a bare metal deployment using the ./oss-k8s.sh script (not the docker container) and I get the following failure because `jmespath` is not installed.

```sh
TASK [kubernetes/sas-iac-buildinfo : Create the sas-iac-buildinfo ConfigMap manifest file] *************************************************************
Friday 08 July 2022  07:27:35 +0000 (0:00:00.372)       0:00:00.982 ***********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: You need to install "jmespath" prior to running json_query filter
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleError: You need to install \"jmespath\" prior to running json_query filter"}`
```

I see it is part of the requirements.txt file and installed when building the docker image, but it should be part of the documented requirements when not using the docker image.

**Comment by thpang** [comment]
Yeah that one is also tricky as it uses `terraform` so the login around adding in the iac-buildinfo into the cluster needs to be revisited. We'll look at adding the required list of tools here as well.

**Comment by jarpat** [comment]
Internal ticket created for this doc update.
