### ISSUE TITLE
(IAC-716) Doc improvement : provide inventory sample without postgres Host groups

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-k8s#16]
In order to disable the external postgres I had to remove and comment specific lines in the default/example inventory file.
People with limited knowledge of ansible might struggle to do it.
It would be nice so provide an inventory sample without postgres Host groups as it corresponds to deployment with internal postgres (which is likely the most common choice).
Thanks

**Comment by thpang** [comment]
Yeah I think we need a sample file for internal postgres.
