### ISSUE TITLE
docs: (IAC-1267) export variables in .bare_metal_creds.env

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-k8s#17]
Here is how I created my own  .bare_metal_creds.env

```sh
# generate a env file with ansible credentials 
bash -c "cat << EOF > ~/.bare_metal_creds.env
export ANSIBLE_USER=cloud-user
export ANSIBLE_PASSWORD=lnxsas
EOF"
chmod 600 ~/.bare_metal_creds.env
```

if I'm not using the "export" commands, the script keeps asking me the ansible credentials.
I would suggest that we add them in the sample.
Thanks

**Comment by raphaelpoumarede** [comment]
thanks @thpang 
In my case though, sourcing the file was not enough to persist the environment through the playbook execution with the oss-k8s.sh I ad to explicity export them so they remain available inside the oss-k8s.sh execution space.

**Comment by thpang** [comment]
That may be true. Looking and I have those values coded in my .zshrc file and labeled as `EXPORT` as well.
