### ISSUE TITLE
small typo in README

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-k8s#39]
Hi there 
It is a very minor issue but I think there is a typo in this sentence : _"At least 1 machine to host a PostgreSQL server (for the SAS Infrastructure Data Server component) if you **are plan** on using an external database server with your cluster"_

**Comment by jarpat** [comment]
Closing, this was resolved as part of the 2.0.0 release. 
The typo is corrected in 2.0.0 and newer versions.
