### ISSUE TITLE
feat: (IAC-1245) add a requirement in the README : all nodes should be at the same time.

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-k8s#40]
For a successful kadmin init step, all the machines in the collection must have the same date and time. 
While not explicitly listed this requirement is very important… if one of the node is 2 minutes behind the others, the installation will not succeed. When trying to connect to your API server you’ll see this kind of error message :

Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2022-09-05T09:11:23Z is before 2022-09-05T09:12:15Z

It might seem obvious that all servers are at the same time, however in a VMWare environment, on boot the VM picks up the time from the BIOS (which would be from the VMWare hosts) and real life experience taught us, that the time could drift on specific VMWare hosts…resulting in different date/time on the collection’s machines.

**Comment by jarpat** [comment]
Internal ticket created.
