### ISSUE TITLE
Remove or comment the kubernetes_vip_interface line in the ansible-vars.yaml sample ?

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-iac-k8s#41]
The **kubernetes_vip_interface** variable is no longer listed in the CONFIG-VARS.md file for vsphere, however it is still listed in the Ansible ansible-vars.yaml file in the same page and also in the [sample](https://github.com/sassoftware/viya4-iac-k8s/blob/1.2.0/examples/bare-metal/sample-ansible-vars.yaml).

**Comment by jarpat** [comment]
Closing this was resolved in PR #37 and is fixed in 2.0.0 and newer releases.
