### ISSUE TITLE
kubernetes/toolbox

### ISSUE THREAD

**Issue by ms3as** [sassoftware/viya4-iac-k8s#49]
Hello,

the role kubernetes/toolbox (Step "Apply Google Cloud public signing key") stops with Error.
The URL https://packages.cloud.google.com/apt/doc/apt-key.gpg return an http 500 error.

BR
Markus

**Comment by jarpat** [comment]
Hey @ms3as, are you still running into this?
I was not able to recreate this issue.

**Comment by jarpat** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-iac-k8s/issues/new).
