### ISSUE TITLE
Update node labelling to work with pattern matching rather than a simple string search

### ISSUE THREAD

**Issue by AWSmith0216** [sassoftware/viya4-iac-k8s#54]
Currently file **roles/kubernetes/node/labels_taints/tasks/main.yaml** does a simple string **find** to determine if the node name matches the key value. It would be nice to enhance this so that we could have the capability to match on a regex pattern as well. This would allow users to set a key such as ".+" to match on all node names.

**Comment by AWSmith0216** [comment]
Entered pull request #60 to resolve this.

**Comment by jarpat** [comment]
Closing, released as part of 3.5.0
https://github.com/sassoftware/viya4-iac-k8s/releases/tag/3.5.0
