### ISSUE TITLE
Remove references to delphi.unx.sas.com

### ISSUE THREAD

**Issue by AWSmith0216** [sassoftware/viya4-iac-k8s#56]
[In roles/systems/common/tasks/main.yaml](https://github.com/sassoftware/viya4-iac-k8s/blob/544ca8cd9463d4f37633655947885d67bbbef7bf/roles/systems/common/tasks/main.yaml#L92) and [roles/kubernetes/common/tasks/main.yaml](https://github.com/sassoftware/viya4-iac-k8s/blob/544ca8cd9463d4f37633655947885d67bbbef7bf/roles/kubernetes/common/tasks/main.yaml#L119), certificate CA files are pulled from delphi.unx.sas.com. This is an internal SAS URL and should not be referenced. I don't believe the SAS CA is needed for anything in this project, so the whole "Adding SAS certs" task could likely be removed.

**Comment by jarpat** [comment]
Closing this, this was resolved as part of PR #81 and the fix has been available since the 3.4.0 release.
