### ISSUE TITLE
fix: (IAC-1246) Declare "cluster_node_pool_mode" in variables.tf to remove warning message

### ISSUE THREAD

**Issue by AWSmith0216** [sassoftware/viya4-iac-k8s#57]
Using the 'minimal' example file, I get the following warning message after running the apply:

```
Warning: Value for undeclared variable

The root module does not declare a variable named "cluster_node_pool_mode"
but a value was found in file "terraform.tfvars".
If you meant to use this value, add a "variable" block to the configuration.
```

Seems like this variable should either be declared in variables.tf, or removed from the example and output files.

**Comment by jarpat** [comment]
Internal ticket created.

**Comment by jarpat** [comment]
Closing, the fix was merged and is available in the staging branch. It will be included in the next upcoming release.
