### ISSUE TITLE
sample-inventory is not correct

### ISSUE THREAD

**Issue by hobsas** [sassoftware/viya4-iac-k8s#65]
Hi,

Could you please add the postgres_server_name paramètre on the examples/bare-metal/sample-inventory or fixe the roles/systems/postgres/tasks/main.yaml?
Because if it's not set the IaC raise the following error:

fatal: [10.96.14.146]: FAILED! => {"msg": "The conditional check 'postgres_server_name != \"default\"' failed. The error was: error while evaluating conditional (postgres_server_name != \"default\"): 'postgres_server_name' is undefined\n\nThe error appears to be in '/home/cloud-user/viya4-iac-k8s/roles/systems/postgres/tasks/main.yaml': line 201, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create admin postgres user\n  ^ here\n"}

Best regards

**Comment by jarpat** [comment]
Hey @hobsas, 

Good catch, working on getting a PR created for this. I'll link it to this issue.

**Comment by jarpat** [comment]
Linking #69

**Comment by jarpat** [comment]
Closing this, the fix is included in the 3.1.0 release
https://github.com/sassoftware/viya4-iac-k8s/releases/tag/3.1.0
