### ISSUE TITLE
IaC didn't update postgresql.conf

### ISSUE THREAD

**Issue by hobsas** [sassoftware/viya4-iac-k8s#66]
Hi,

I found that the IaC didn't update the max_connections and max_prepared_transactions on the postgresql.conf.

See below my config:

[test_k8s_default_pgsql]
sasnode03
[test_k8s_default_pgsql:vars]
postgres_server_name = "default"
postgres_ip="10.96.14.146"
postgres_server_version="12"
postgres_server_ssl="off"
postgres_administrator_login="postgres"
postgres_administrator_password="admin123"
postgres_system_setting_max_prepared_transactions="1024"
postgres_system_setting_max_connections="1024"

[postgres:children]
test_k8s_default_pgsql

After the IaC created the DB:

ps -efl | grep postgresql
0 S postgres   98448       1  0  80   0 - 53888 -      09:20 ?        00:00:00 /usr/lib/postgresql/12/bin/postgres -D /var/lib/postgresql/12/main -c config_file=/etc/postgresql/12/main/postgresql.conf

egrep 'max_connections|max_prepared_transactions' /etc/postgresql/12/main/postgresql.conf
max_connections = 100                   # (change requires restart)
#max_prepared_transactions = 0          # zero disables the feature
# Caution: it is not advisable to set max_prepared_transactions nonzero unless

Regards

**Comment by raphaelpoumarede** [comment]
I can see the same thing (bare metal mode) with postgres 14
I have the same settings in my inventory file :

```sh
postgres_system_setting_max_prepared_transactions="1024"
postgres_system_setting_max_connections="1024"
```
But the value in the /etc/postgresql/14/main/postgresql.conf for max_connection remains the default value (100)

```sh
max_connections = 100                   # (change requires restart)
```

**Comment by jarpat** [comment]
Hey @hobsas & @raphaelpoumarede 

The `max_connections` and `max_prepared_transactions` are set using the `ALTER SYSTEM` SQL command here in the code:
https://github.com/sassoftware/viya4-iac-k8s/blob/fdde8c9a728e9eac2ecd48b658465cc8f96f6bf3/roles/kubernetes/database/postgres/alter_server_settings/tasks/main.yaml#L14-L20
 
Relevant snippet from the doc about `ALTER SYSTEM`: https://www.postgresql.org/docs/13/sql-altersystem.html
> ALTER SYSTEM is used for changing server configuration parameters across the entire database cluster. It can be more convenient than the traditional method of manually editing the postgresql.conf file. ALTER SYSTEM writes the given parameter setting to the postgresql.auto.conf file, which is read in addition to postgresql.conf. Setting a parameter to DEFAULT, or using the RESET variant, removes that configuration entry from the postgresql.auto.conf file. Use RESET ALL to remove all such configuration entries.

On your postgres machine if you execute:
```bash
sudo cat /var/lib/postgresql/13/main/postgresql.auto.conf # replace 13 with your version
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
max_prepared_transactions = '1024'
max_connections = '1024'
```

You should see the system settings that are applied inside `postgresql.auto.conf`, These system settings will be loaded along with `postgresql.conf` as sort of an overlay to the settings.

You can also query the postgres db to check the effective settings
```
postgres=# SELECT Name,Setting from pg_settings WHERE name='max_prepared_transactions' OR name='max_connections';
 max_connections           | 1024
 max_prepared_transactions | 1024

postgres=# 

```

**Comment by raphaelpoumarede** [comment]
Thank you @jarpat for the explanations !

**Comment by jarpat** [comment]
No problem.
