### ISSUE TITLE
how to push images to Container Registry (harbor)

### ISSUE THREAD

**Issue by medhatmamdouhsas** [sassoftware/viya4-iac-k8s#89]
hello, 
i used this IAC to setup pare metal cluster.
the thing related to CR is not clear, what will be the port ,URL, username and password. that should be passed to viya4-Deployment.
[viya4-deployment](https://github.com/sassoftware/viya4-deployment) is talking about tfstate but it's not created here and not used

**Comment by jarpat** [comment]
That feature snuck in there, currently we can provision a machine for CR but the installation process is not yet implemented.
I will be updating the example files/doc to remove that and add a TODO file for the CR installation.
